steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/hobby-440408/skudo-repo/skudo-app:latest', '.']
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/hobby-440408/skudo-repo/skudo-app:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'skudo-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/hobby-440408/skudo-repo/skudo-app:latest'
      - '--region'
      - 'us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
